[package]
name = "cs_cityio_backend"
version = "0.1.0"
authors = ["yasushi"]
edition = "2018"

[dependencies]
url = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

bytes="0.4"
futures="0.1"
log="0.4"
env_logger="*"

actix-web = "1.0.0-beta.4"
actix-files = "0.1.0-beta.4"
diesel = { version = "1.0.0", features = ["postgres", "serde_json", "chrono", "r2d2"] }
dotenv = "0.9.0"
chrono= { version = "0.4", features = ["serde"] }

sha256 = { path="../sha256" }
